trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
    
  - task: Bash@3
    inputs:
      filePath: './cicd-api.sh'

  - task: PublishTestResults@2
    displayName: 'publish testsigma test results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-report.xml'
